% FUNCTION TO PLOT BAR GRAPH OF PUPIL CENTER DISTANCE STANDARD DEVIATION

% CODE AUTHORED BY: SHAWHIN TALEBI
% THE UNIVERSITY OF TEXAS AT DALLAS
% MULTI-INTEGRATED REMOTE SENSING AND SIMULATION (MINTS)

function axPDD = visualizePCD_SD(TobiiTimetable, ts, cmap)

    b = bar(...
        TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness(ts));
    b.Parent.XLim = [0.25 1.75];
    b.Parent.YLim = [0 1.1*...
        max(TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness)];
    try
        b.FaceColor = cmap(...
            round((256*...
            TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness(ts)...
            /max(TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness))),:);
    catch
    end
    axPDD = gca; axPDD.XTickLabel = '';
    axPDD.YAxis.FontSize = 16;
    axPDD.Title.String = {'Pupil Distance'; 'Representativeness (mm)'};
    axPDD.Title.FontSize = 18;

    % update text with difference between pupil sizes
    if ~isnan(TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness(ts))
        text(1, ...
            max(TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness),...
            string(...
            round(...
            TobiiTimetable.PupilCenter_Distance_MovingRepresentativeness(ts)...
            ,2)), ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 20)
    end
    