% FUNCTION TO VISUALIZE PUPIL DIAMETERS

% CODE AUTHORED BY: SHAWHIN TALEBI
% THE UNIVERSITY OF TEXAS AT DALLAS
% MULTI-INTEGRATED REMOTE SENSING AND SIMULATION (MINTS)

function axPD = visualizePD(TobiiTimetable, ts)

    % define left and right eye horizontal locations
    LeftEyePositionX = nanmean(TobiiTimetable.PupilCenterX_LeftPupilCenter_Timetable);
    RightEyePositionX = nanmean(TobiiTimetable.PupilCenterX_RightPupilCenter_Timetable);
    eyePositionY = mean(...
        [nanmean(TobiiTimetable.PupilCenterY_LeftPupilCenter_Timetable) ...
        nanmean(TobiiTimetable.PupilCenterY_RightPupilCenter_Timetable)]);

    % define Y position for text
    textPositionY = -1.25*mean(...
        [nanmean(TobiiTimetable.PupilCenterY_LeftPupilCenter_Timetable) ...
        nanmean(TobiiTimetable.PupilCenterY_RightPupilCenter_Timetable)]);

    % clear axis
    cla
    
    % create outline of left eye
    scatter(LeftEyePositionX, eyePositionY, ...
    'Marker', 'o',...
    'LineWidth', 1, ...
    'Cdata', [0.3010 0.7450 0.9330],...
    'SizeData', 7500)

    % turn hold on to plot additional items on axis
    hold on
    
    % define axis handle
    axPD = gca;
    % set axis limits
    axPD.XLim = ...
    [1.5*min(TobiiTimetable.PupilCenterX_RightPupilCenter_Timetable) ...
    1.5*max(TobiiTimetable.PupilCenterX_LeftPupilCenter_Timetable)];
    axPD.YLim = ...    
        [1.7*min(TobiiTimetable.PupilCenterX_RightPupilCenter_Timetable) ...
        1.5*max(TobiiTimetable.PupilCenterX_LeftPupilCenter_Timetable)];

    % remove x and y tick marks
    axPD.XTick = [];
    axPD.YTick = [];

    % create outline of right eye
    scatter(RightEyePositionX, eyePositionY, ...
    'Marker', 'o',...
    'LineWidth', 1, ...
    'Cdata', [0.3010 0.7450 0.9330],...
    'SizeData', 7500)
    
    
    % plot visualize left pupil diameter
    scatter(TobiiTimetable.PupilCenterX_LeftPupilCenter_Timetable(ts), ...
        TobiiTimetable.PupilCenterY_LeftPupilCenter_Timetable(ts), ...
        'filled', ...
        'Marker', 'o', ...
        'Cdata', [0 0 0], ...
        'SizeData', 380*TobiiTimetable.PupilDiameter_LeftPupilDiameter_Timetable(ts));
    % add numeric label with pupil size in mm
    if ~isnan(TobiiTimetable.PupilDiameter_LeftPupilDiameter_Timetable(ts))
        text(LeftEyePositionX, textPositionY,...
            string(round(TobiiTimetable.PupilDiameter_LeftPupilDiameter_Timetable(ts),1)), ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 20)
    end

    % plot visualize right pupil diameter
    scatter(TobiiTimetable.PupilCenterX_RightPupilCenter_Timetable(ts), ...
        TobiiTimetable.PupilCenterY_RightPupilCenter_Timetable(ts), ...
        'filled', ...
        'Marker', 'o', ...
        'Cdata', [0 0 0], ...
        'SizeData', 380*TobiiTimetable.PupilDiameter_RightPupilDiameter_Timetable(ts));
    % add numeric label with pupil size in mm
    if ~isnan(TobiiTimetable.PupilDiameter_RightPupilDiameter_Timetable(ts))
        text(RightEyePositionX, textPositionY,...
            string(round(TobiiTimetable.PupilDiameter_RightPupilDiameter_Timetable(ts),1)), ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 20)
    end
    
    % add a title
    axPD.Title.String = 'Pupil Size and Position (mm)';
    axPD.Title.FontSize = 20;
    
    
end